# Workflows: .github/workflows/*.yml
name: GitHub Actions Demo
# Events: workflow触发事件
on: [push]
# Jobs: steps集合
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            # Actions: 常见复杂重复性工作
            - name: Check out repository code
              uses: actions/checkout@v3
            - run: echo "Hello Github Action!"
